import '../../desktop/Component.spec.tsx'
import '../Data/actions/save.spec.ts'
import '../Factory/common/set.spec.ts'
import '../Factory/editable/changed.signal.spec.ts'
import '../Factory/editable/finishEditing.spec.ts'
import '../Status/actions/status.spec.ts'