export const RECEIVE_LIBRARY = 'RECEIVE_LIBRARY'
export const REFRESHING_LIBRARY = 'REFRESHING_LIBRARY'
export const REFRESHING_LIBRARY_ERROR = 'REFRESHING_LIBRARY_ERROR'
export const FILES_ADD = 'FILES_ADD'
