import { Translation } from '../translate'

export const en: Translation =
{ emailPlaceholder: 'Email...'
, lang: 'English'
, passwordPlaceholder: 'Password...'
, repeatPasswordPlaceholder: 'Repeat password...'
, AuthenticatingTitle: 'Authenticating...'
, CancelBtn: 'Cancel'
, Class: 'class'
, ClassS: 'classes'
, DictationTab: 'Dictation'
, EmptyPlaceholder: 'Type your text here...'
, Document: 'document'
, DocumentS: 'documents'
, Folder: 'folder'
, FolderS: 'folders'
, InvalidPasswordError: 'Invalid password.'
, LoadingTitle: 'Loading Sarigama...'
, LoginTitle: 'Please login'
, LogoutBtn: 'Logout'
, NavigatorTitle: 'Navigation'
, NewBtn: 'New'
, NewDocumentTitle: 'New Document'
, NoTitle: 'No Title'
, RegisterBtn: 'Register'
, PasswordsDoNotMatchError: 'Password entries do not match.'
, SaveBtn: 'Save'
, SetPasswordBtn: 'Set Password'
, SetPasswordTitle: 'Set master password'
, SignInBtn: 'Sign In'
, SignInWithGoogleBtn: 'Sign-in with Google'
, SignInWithFacebookBtn: 'Sign-in with Facebook' 
, ScoreTab: 'Sheets'
, Student: 'student'
, StudentS: 'students'
, SyncTitle: 'Synchronization...'
, TrustUserBtn: 'Trust'
, TrustUserTitle: 'Trust User'
, TrustKeysBtn: 'Copy trust link'
, TrustKeysCopiedBtn: 'Link copied !'
, TypeTextHere: 'Enter text here...'
, TypeTitleHere: 'Document title...'
, UnlockBtn: 'Unlock'
, UnlockTitle: 'Unlock with master password'
}
