import { Translation } from '../translate'

export const fr: Translation =
{ emailPlaceholder: 'Email...'
, lang: 'Français'
, passwordPlaceholder: 'Mot de passe...'
, repeatPasswordPlaceholder: 'Répéter le mot de passe...'
, AuthenticatingTitle: 'Vérification d\'accès...'
, CancelBtn: 'Annuler'
, Class: 'Classe'
, ClassS: 'Classes'
, DictationTab: 'Dictée'
, Document: 'Document'
, DocumentS: 'Documents'
, EmptyPlaceholder: 'Écrivez votre texte ici...'
, Folder: 'Cahier'
, FolderS: 'Cahiers'
, InvalidPasswordError: 'Mot de passe eronné.'
, LoadingTitle: 'Chargement de Sarigama...'
, LoginTitle: 'Veuillez vous identifier'
, LogoutBtn: 'Déconnection'
, NavigatorTitle: 'Navigation'
, NewBtn: 'Nouveau'
, NewDocumentTitle: 'Nouveau Document'
, NoTitle: 'Sans Titre'
, PasswordsDoNotMatchError: 'Les mots de passe ne correspondent pas.'
, RegisterBtn: 'S\'inscrire'
, SaveBtn: 'Enregistrer'
, SetPasswordBtn: 'Définir'
, SetPasswordTitle: 'Choix du mot de passe principal'
, SignInBtn: 'Connection'
, SignInWithGoogleBtn: 'Connection avec Google'
, SignInWithFacebookBtn: 'Connection avec Facebook' 
, ScoreTab: 'Partition'
, Student: 'Élève'
, StudentS: 'Élèves'
, SyncTitle: 'Synchronisation des données...'
, TrustUserBtn: 'Faire confiance'
, TrustUserTitle: 'Faire confiance'
, TrustKeysBtn: 'Copier lien'
, TrustKeysCopiedBtn: 'Lien copié !'
, TypeTextHere: 'Écrire ici...'
, TypeTitleHere: 'Titre du document...'
, UnlockBtn: 'Déverouiller'
, UnlockTitle: 'Déverouiller les données avec le mot de passe.'
}
